apiVersion: v1
preferences: {}
kind: Config

clusters:
- cluster:
    server: https://5400CA252C13A5D77196B7135331FAC2.yl4.eu-west-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EWXlOREV6TVRrMU5sb1hEVE13TURZeU1qRXpNVGsxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVJmCmpvNHZHbmdDQTZNekREclphQVQzNlNjMXNOMVFYd0NLQlgrVUxOUk9LMlVZZGo5TlJJK2VzbkttRE91Q3MwblMKZE9mZmpnWDRrRHhWQlFabHNtc1JTQnZxNExrT3NadHNUdDBKblBaK2s0Y3k3WGtYM0hpcnBiUzRCMHNYR29FYgpWVnArdUN5UDg0MkdjRzhnNHU2cUdkaGxuTWpmMGJjNjh0UUpIbnBNbXNZMGp5dDZodkkrRGFib0hxeDFlRnJDCk01WVpmWW9MNnptRW5kMExIbU4xS3dHRWowWklmZUEweTdBWW1tdy9qeXhKdmtYNFJCcE40S1lvcnBoTFBHUVUKLzNuRFp6U3VwVU0wSGZUZFlKTDNvOTZzR2FyL01jN1lZNnRBTXRFT2luenNKOEU1WkpRZGw0YmpVekQvVlZMeQpaSHZCa2VZcjNjUHU2cVUzeWdrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFSWlEYXhJRVVNLzhGbVRGa3lKbkZCQ0tUeEoKUlV4QnVvOE1PblpQUy9zZmp6NStBRjdFRHIzVzQrZGxLdWcyL0IxK0ZYMElqOERVTTg1bUZ0MzNKWUh1bjhGcQpsT2FnT3VqVFZUZytIRC9FcFhJVit5Z2ZnNkRVREtEcTVYdEN6Z0NSZ3psLzNJUklwYmNGNTBZNUI5NWFJWEpRCmtva2pWTkhleUVUSW5pUThocy9TZHRad0dURXRIVGpOaEsrbmN6WlA1YTBQZE1TcUYyL1FLVENqV1AzTis3YWQKVmljMWdGcVJaOU44WDVtb0ZVd0h4L2VkcmZHRkR1SE9oV1ExWFlSRVlBNCtpeEpYNlBZeW81Yy9QZDROaWhjNQpxemFsN2pYTzljMVMwR3JXaEsycTNrMVVJUmhPcnJoUjVlc2hWTHlxbDdVY2F3NzRQTERTQTJNcGVYZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  name: eks_ci-cd-cluster-NYy4tv7q

contexts:
- context:
    cluster: eks_ci-cd-cluster-NYy4tv7q
    user: eks_ci-cd-cluster-NYy4tv7q
  name: eks_ci-cd-cluster-NYy4tv7q

current-context: eks_ci-cd-cluster-NYy4tv7q

users:
- name: eks_ci-cd-cluster-NYy4tv7q
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "ci-cd-cluster-NYy4tv7q"
